### ISSUE TITLE
Router, route and layout query property

### ISSUE THREAD

**Issue by Biromain** [ventoviro/windwalker-joomla-rad#131]
`Windwalker\Router\Route::build()` don't care about layout property and select bad item link url (select first item match without layout). Or i don't understand something about router.

Regards,

**Comment by asika32764** [comment]
We haven't wrote Router document because router will be total rewrite in 2.1.

Currently you must add layout in URL pattern.

```
/foo/bar/:alias/:layout
```

Or use the callback.

``` json
{
	"sakura": {
		"pattern": "sakura/:id/:alias",
		"view" : "sakura",
		"buildHandler" : ["ClasName", "method"],
		"parseHandler" : ["ClasName", "method"],
	}
}
```

And if you want to build route, please use `_()`

Example:

``` php
\Flower\Router\Route::_('com_flower.sakura', ['id' => 5]);

// OR ignore component name and auto detect

\Flower\Router\Route::_('sakura', ['id' => 5]);
```

**Comment by Biromain** [comment]
Thank you :+1:
