### ISSUE TITLE
Singular model and join

### ISSUE THREAD

**Issue by Biromain** [ventoviro/windwalker-joomla-rad#132]
We can specify table links in plural model but when I go to the page of an element (with the singular model) I have no information from other tables. Will you guide me on what to do?

Regards,

**Comment by asika32764** [comment]
Singular model use `JTable` to get item, so we won't use join to get  information from other tables.

The simplest way is override the `getItem()` like we used to in Joomla.

``` php
function getItem($pk = null)
{
    $item = parent::getItem($pk);

    if ($item)
    {
        // Load other tables
    }

    return $item;
}
```

An other way is that write it in `JTable` of this record, but I'm not recommend to go this way because we should keep ActiveRecord layer cleaner and write necessary logic in Model.

**Comment by Biromain** [comment]
Can you explain me how to load other tables please?

**Comment by skylying** [comment]
The easiest way is to use `DataMapper` class

```php
public function getItem($pk = null)
	{
		$appleTable = new DataMapper(Table::APPLES);
		$item = $appleTable->findOne(array('id' => 1));

		var_dump($item);

		return parent::getItem($pk);
	}
```

You can simply replace `Table::APPLES` into pure text format of your table name 
And DataMapper also provide other query methods, feel free to check the source.

**Comment by skylying** [comment]
Don't forget the namespace 
`use Windwalker\DataMapper\DataMapper;`

**Comment by asika32764** [comment]
There will be several ways to get other tables.

One is use `Model::getTable()`

``` php
function getItem($pk = null)
{
    $item = parent::getItem($pk);

    if ($item)
    {
        $appleTable = $this->getTable('Apple', 'Fruit');

        $appleTable->load($item->apple_id);

        $item->apple = $appleTable->getProperties();
    }

    return $item;
}
```

Or use `JTable::getInstance()`

``` php
$appleTable = JTable('Apple', 'Fruit');
```

These ways are same as Joomla native.

**Comment by asika32764** [comment]
@skylying mentioned the `DataMapper`, it will be useful when you want to get multiple relation items.

**Comment by asika32764** [comment]
> Don't forget the namespace 
> use Windwalker\DataMapper\DataMapper;

Should be `Windwalker\Joomla\DataMapper\DataMapper` in 2.0

**Comment by Biromain** [comment]
Thank you all !
