### ISSUE TITLE
Quickadd for user

### ISSUE THREAD

**Issue by Biromain** [ventoviro/windwalker-joomla-rad#135]
Hi,

Can i have some clue about the best way to make a quickadd for user form field?

Regards,

**Comment by asika32764** [comment]
Do you want to add a new user or simply add user field in quickadd?

**Comment by Biromain** [comment]
I created a table extends user fields and i would like adding a joomla user on the fly when i'm on extended fields form.

**Comment by asika32764** [comment]
Maybe you must customize your own model to do this.

See: https://github.com/ventoviro/windwalker-joomla-rad/blob/dev-2.1/src/Controller/Ajax/QuickaddController.php#L40-L42

https://github.com/ventoviro/windwalker-joomla-rad/blob/dev-2.1/src/Form/Fields/itemlist.php#L336

You can add some URL params to custom the Model handler.

For example, add `view_item="user"` 

Write user quickadd fields definition in `model/form/user.xml`

And create a model named `User` in your component.

Now quickadd controller will call `XxxModelUser::save()` to create this record. You must write your user create logic in this model.

**Comment by asika32764** [comment]
Quickadd is too old and rusty since it has been created from 1.0

I will rewrite it to be more simple to use after 2.1
