### ISSUE TITLE
Infinite loop in Batch\CopyController

### ISSUE THREAD

**Issue by Dagolin** [ventoviro/windwalker-joomla-rad#167]
It goes into an infinite loop if the a table has no `incrementFields` like `title` or `alias`.

See : https://github.com/ventoviro/windwalker-joomla-rad/blob/020bfd02baddade151662421aa83a30fd6a38c93/src/Controller/Batch/CopyController.php#L58-L71

**Comment by asika32764** [comment]
Fixed with https://github.com/ventoviro/windwalker-joomla-rad/commit/8adc1fc84af951dd2e2a94536fb55f20715ff010

And 2.1.2 released
