### ISSUE TITLE
Issue with Caching and closure serialization

### ISSUE THREAD

**Issue by Skullbock** [ventoviro/windwalker-joomla-rad#176]
Hi there, using asikart component i'm getting a "Closure is not serializable" error.
I got it back to:

https://github.com/ventoviro/windwalker-joomla-rad/blob/staging/src/Model/ListModel.php#L349

Where the cache call tries for some reason to serialize the callable there.
just reporting to let you guys test it 

Cheers

**Comment by asika32764** [comment]
Hi 

thank you for reporting this issue.

Which component you use and got this message?
