### ISSUE TITLE
getState statement typo in CrudModel

### ISSUE THREAD

**Issue by Dagolin** [ventoviro/windwalker-joomla-rad#204]
L:128
https://github.com/ventoviro/windwalker-joomla-rad/blob/staging/src/Model/CrudModel.php#L128

`$pk  = \JArrayHelper::getValue($data, $key, $this->getState($this->getName() . '.id'));`

should be

`pk  = \JArrayHelper::getValue($data, $key, $this->getState()->get($this->getName() . '.id'));`

**Comment by asika32764** [comment]
Could you create a PR to fix this issue direct to branch `2.0`? (You are still using 2.0 right?)
