### ISSUE TITLE
Release 2.1.15 not available for joomla 3.8.X

### ISSUE THREAD

**Issue by vinespie** [ventoviro/windwalker-joomla-rad#278]
There is an error in [manifest file for update](https://raw.githubusercontent.com/ventoviro/windwalker-joomla-rad/staging/update.xml). 

Release 2.1.15 is only available for joomla versions <= 3.7.X

**Comment by asika32764** [comment]
OK, it's a mistake. I'll fix it soon.

**Comment by asika32764** [comment]
Now it should able to update in 3.8

Thank you for reporting this issue.

![p-2017-10-23-001](https://user-images.githubusercontent.com/1639206/31897625-892e8f0a-b849-11e7-8e24-b87b4250c3a4.jpg)
