### ISSUE TITLE
.exe file in install

### ISSUE THREAD

**Issue by iamrobert** [ventoviro/windwalker-joomla-rad#283]
I'm finding the following file:
hiddeninput.exe

In this folder:
/libraries/windwalker/vendor/windwalker/console/bin

Why does it need an .exe file?

I also have a warning in GWT about "Harmful Content". Specifically "Uncommon Downloads
Some or all of the downloads on this site are showing "uncommon download" warnings."

So - I'm thinking it could be caused by this?

**Comment by iamrobert** [comment]
1. I have installed on a default joomla (https://demo.joomla.org/)
2. After upgrading windwalker framework - its there.

![Image of Problem](https://i.imgur.com/iD9Yvje.png)

Joomla site download:
https://we.tl/QVFpJvqdEn

**Comment by asika32764** [comment]
Hi, please see https://github.com/asikart/remoteimage/issues/54 and https://github.com/Seldaek/hidden-input

This is a helper file for Windows to make password field be hidden in command line application.

This file is part of Windwalker console and Symfony console. And we use Windwalker console as our framework.

If you have security concern, you can just remove this file and keep framework ad extension still works in web side.

**Comment by iamrobert** [comment]
Thanks Simon - btw the .exe is not suspicious as I deleted it and still get the issue.
