### ISSUE TITLE
Cannot use Object as a class name. Reserved in PHP 7.2

### ISSUE THREAD

**Issue by Skullbock** [ventoviro/windwalker-joomla-rad#292]
Since php 7.2 "Object" is a reserved keyword. 
The "Object" class in WindWalker needs to be renamed otherwise it causes a fatal error in any php 7.2 environment.

http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by asika32764** [comment]
2.1.19 released to fix Object keyword issue.
https://github.com/ventoviro/windwalker-joomla-rad/releases/tag/2.1.19
