### ISSUE TITLE
Model support tags

### ISSUE THREAD

**Issue by asika32764** [ventoviro/windwalker-joomla-rad#8]
_Issue by **[asika32764](https://github.com/asika32764)** from Friday Jan 10, 2014 at 12:32 GMT_
_Originally opened as https://github.com/ventoviro/windwalker/issues/19_

----

**Comment by Biromain** [comment]
Any news about this feature?

**Comment by asika32764** [comment]
We haven't do this yet. There are many work processing slowly at 2.1 branch.

**Comment by asika32764** [comment]
But to my experience, we don't need model to support tags, simply follow this guide that we can add tags supporting to our component.
https://docs.joomla.org/J3.x:Using_Tags_in_an_Extension

**Comment by asika32764** [comment]
UCM will be deprecated, closed.
